// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toxrnccgpjcwodxjyjlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRveHJuY2NncGpjd29keGp5amxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzMyODksImV4cCI6MjA3Mzg0OTI4OX0.gnjKb0AoY5cvq_9QzZcemq2_FWhrYX73vYzoNhmkKPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});